joint1_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a1
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint2_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a2
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint3_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a3
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint4_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a4
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint5_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a5
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0
joint6_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a6
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0
joint7_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_a7
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0
#gazebo_ros_control:
#        pid_gains:
#                joint_a1: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a2: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a3: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a4: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a5: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a6: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a7: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50








 
