iiwa_controller:
  type: velocity_controllers/JointVelocityController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    - joint_a7
  gains:
    joint_a1: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a2: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a3: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a4: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a5: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a6: {p: 100, d: 1, i: 1, i_clamp: 1}
    joint_a7: {p: 100, d: 1, i: 1, i_clamp: 1}
#gazebo_ros_control:
#        pid_gains:
#                joint_a1: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a2: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a3: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a4: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a5: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a6: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
#                joint_a7: {p: 10.0, i: 1, d: 1.0, i_clamp: 1}
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50








 
